In [ ]:
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [5]:
data=pd.read_csv('Churn_Modelling.csv')

In [7]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [14]:
print(data.columns)

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='str')

In [15]:

data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [16]:
#encoding categorical data
labelencoder_gender=LabelEncoder()
data['Gender']=labelencoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [18]:
#one hot encoding for geography column
from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder()
geo=onehotencoder.fit_transform(data[['Geography']])
geo

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [19]:
onehotencoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [22]:
geo_df=pd.DataFrame(geo.toarray(),columns=onehotencoder.get_feature_names_out(['Geography']))
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [23]:
#combine
data=pd.concat([data,geo_df],axis=1)

In [24]:
data=data.drop(['Geography'],axis=1)

In [25]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [27]:
###save the encoder
with open('labelencoder_gender.pkl','wb') as file:
    pickle.dump(labelencoder_gender,file)
with open('onehotencoder.pkl','wb') as file:
    pickle.dump(onehotencoder,file)

In [31]:
# Divinding dataset into dependent and independent variables
X=data.drop(['Exited'],axis=1)
y=data['Exited']

##Split in training and testing data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

##Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [32]:
X_train

array([[ 0.16958176, -1.09168714, -0.46460796, ..., -1.01460667,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -1.01460667,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  0.98560362,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  0.98560362,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ..., -1.01460667,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ..., -1.01460667,
         1.75486502, -0.57369368]])

In [33]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [34]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [36]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [37]:
#BUilding the ANN model
model=Sequential([
    Dense(64, activation='relu',input_shape=(X_train.shape[1],)),#first hidden layer
    Dense(32, activation='relu'),#second hidden layer
    Dense(1, activation='sigmoid')#output layer
])

WARNING:tensorflow:From c:\Users\Riyanshi Gupta\Classification_With_ANN\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
##compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:From c:\Users\Riyanshi Gupta\Classification_With_ANN\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [42]:
 ##setup the tensorboard

from tensorflow.keras.callbacks import TensorBoard,EarlyStopping


log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [45]:
#early stopping to avoid overfitting
early_stopping=EarlyStopping(monitor='val_loss', patience=10,   restore_best_weights=True)

In [46]:
##Train the model
history=model.fit(X_train,y_train,validation_data=(X_train, y_train),epochs=100,batch_size=32,callbacks=[tensorflow_callback,early_stopping])

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2413 - accuracy: 0.8989 - val_loss: 0.2326 - val_accuracy: 0.9031
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2411 - accuracy: 0.9004 - val_loss: 0.2285 - val_accuracy: 0.9071
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2422 - accuracy: 0.8990 - val_loss: 0.2267 - val_accuracy: 0.9084
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2403 - accuracy: 0.8994 - val_loss: 0.2267 - val_accuracy: 0.9049
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2410 - accuracy: 0.8994 - val_loss: 0.2298 - val_accuracy: 0.9074
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2406 - accuracy: 0.8970 - val_loss: 0.2297 - val_accuracy: 0.9031
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2409 - accuracy: 0.8969 - val_loss: 0.2275 - val_accuracy: 0.9041
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2386 - accuracy: 0.9013 - val_loss: 0.2243 - val_accuracy: 0.9064
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2393 - accuracy: 0.8981 - val_loss: 0.2347 - val_accuracy: 0.9015
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2374 - accuracy: 0.9018 - val_loss: 0.2334 - val_accuracy: 0.9019
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2370 - accuracy: 0.9007 - val_loss: 0.2243 - val_accuracy: 0.9066
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2377 - accuracy: 0.9005 - val_loss: 0.2260 - val_accuracy: 0.9070
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2368 - accuracy: 0.8991 - val_loss: 0.2222 - val_accuracy: 0.9091
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2361 - accuracy: 0.9010 - val_loss: 0.2202 - val_accuracy: 0.9091
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2362 - accuracy: 0.8995 - val_loss: 0.2250 - val_accuracy: 0.9076
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2367 - accuracy: 0.8991 - val_loss: 0.2256 - val_accuracy: 0.9049
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2361 - accuracy: 0.8989 - val_loss: 0.2210 - val_accuracy: 0.9082
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2365 - accuracy: 0.9015 - val_loss: 0.2199 - val_accuracy: 0.9084
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2334 - accuracy: 0.9014 - val_loss: 0.2196 - val_accuracy: 0.9120
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2331 - accuracy: 0.9021 - val_loss: 0.2192 - val_accuracy: 0.9100
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2317 - accuracy: 0.9016 - val_loss: 0.2276 - val_accuracy: 0.9032
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2318 - accuracy: 0.9030 - val_loss: 0.2164 - val_accuracy: 0.9091
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2312 - accuracy: 0.8996 - val_loss: 0.2268 - val_accuracy: 0.9074
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2317 - accuracy: 0.9019 - val_loss: 0.2218 - val_accuracy: 0.9056
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2315 - accuracy: 0.9020 - val_loss: 0.2297 - val_accuracy: 0.9041
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2289 - accuracy: 0.9054 - val_loss: 0.2211 - val_accuracy: 0.9079
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2312 - accuracy: 0.9043 - val_loss: 0.2204 - val_accuracy: 0.9090
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2310 - accuracy: 0.9011 - val_loss: 0.2213 - val_accuracy: 0.9084
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2283 - accuracy: 0.9041 - val_loss: 0.2186 - val_accuracy: 0.9104
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2303 - accuracy: 0.9010 - val_loss: 0.2133 - val_accuracy: 0.9109
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2269 - accuracy: 0.9036 - val_loss: 0.2159 - val_accuracy: 0.9119
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2272 - accuracy: 0.9068 - val_loss: 0.2118 - val_accuracy: 0.9124
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2275 - accuracy: 0.9064 - val_loss: 0.2166 - val_accuracy: 0.9078
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2249 - accuracy: 0.9030 - val_loss: 0.2156 - val_accuracy: 0.9075
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2243 - accuracy: 0.9050 - val_loss: 0.2134 - val_accuracy: 0.9106
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2270 - accuracy: 0.9055 - val_loss: 0.2158 - val_accuracy: 0.9085
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2274 - accuracy: 0.9034 - val_loss: 0.2193 - val_accuracy: 0.9072
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2256 - accuracy: 0.9031 - val_loss: 0.2113 - val_accuracy: 0.9095
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2231 - accuracy: 0.9076 - val_loss: 0.2139 - val_accuracy: 0.9085
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2240 - accuracy: 0.9021 - val_loss: 0.2190 - val_accuracy: 0.9089
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2253 - accuracy: 0.9035 - val_loss: 0.2069 - val_accuracy: 0.9144
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2222 - accuracy: 0.9046 - val_loss: 0.2117 - val_accuracy: 0.9116
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2213 - accuracy: 0.9072 - val_loss: 0.2133 - val_accuracy: 0.9105
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2213 - accuracy: 0.9057 - val_loss: 0.2093 - val_accuracy: 0.9104
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2221 - accuracy: 0.9080 - val_loss: 0.2133 - val_accuracy: 0.9101
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2194 - accuracy: 0.9070 - val_loss: 0.2061 - val_accuracy: 0.9124
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2195 - accuracy: 0.9047 - val_loss: 0.2117 - val_accuracy: 0.9090
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2232 - accuracy: 0.9029 - val_loss: 0.2053 - val_accuracy: 0.9129
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2194 - accuracy: 0.9056 - val_loss: 0.2062 - val_accuracy: 0.9141
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2180 - accuracy: 0.9065 - val_loss: 0.2026 - val_accuracy: 0.9171
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2206 - accuracy: 0.9046 - val_loss: 0.2008 - val_accuracy: 0.9144
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2195 - accuracy: 0.9061 - val_loss: 0.2061 - val_accuracy: 0.9165
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2165 - accuracy: 0.9089 - val_loss: 0.2071 - val_accuracy: 0.9150
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2168 - accuracy: 0.9097 - val_loss: 0.2087 - val_accuracy: 0.9111
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2167 - accuracy: 0.9080 - val_loss: 0.2044 - val_accuracy: 0.9136
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2155 - accuracy: 0.9103 - val_loss: 0.2092 - val_accuracy: 0.9099
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2180 - accuracy: 0.9050 - val_loss: 0.2007 - val_accuracy: 0.9184
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2155 - accuracy: 0.9125 - val_loss: 0.2120 - val_accuracy: 0.9075
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2173 - accuracy: 0.9087 - val_loss: 0.2057 - val_accuracy: 0.9131
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2135 - accuracy: 0.9087 - val_loss: 0.2019 - val_accuracy: 0.9195
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2143 - accuracy: 0.9080 - val_loss: 0.2096 - val_accuracy: 0.9131
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2156 - accuracy: 0.9096 - val_loss: 0.2060 - val_accuracy: 0.9130
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2123 - accuracy: 0.9096 - val_loss: 0.2000 - val_accuracy: 0.9164
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2144 - accuracy: 0.9071 - val_loss: 0.1965 - val_accuracy: 0.9194
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2128 - accuracy: 0.9087 - val_loss: 0.1983 - val_accuracy: 0.9165
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2140 - accuracy: 0.9094 - val_loss: 0.1967 - val_accuracy: 0.9147
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2125 - accuracy: 0.9081 - val_loss: 0.1986 - val_accuracy: 0.9162
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2151 - accuracy: 0.9089 - val_loss: 0.1965 - val_accuracy: 0.9210
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2105 - accuracy: 0.9086 - val_loss: 0.1973 - val_accuracy: 0.9200
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2112 - accuracy: 0.9115 - val_loss: 0.2028 - val_accuracy: 0.9155
Epoch 71/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2109 - accuracy: 0.9109 - val_loss: 0.1920 - val_accuracy: 0.9195
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2112 - accuracy: 0.9100 - val_loss: 0.1974 - val_accuracy: 0.9176
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2115 - accuracy: 0.9110 - val_loss: 0.1908 - val_accuracy: 0.9226
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2100 - accuracy: 0.9122 - val_loss: 0.1920 - val_accuracy: 0.9219
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2103 - accuracy: 0.9126 - val_loss: 0.1925 - val_accuracy: 0.9194
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2080 - accuracy: 0.9114 - val_loss: 0.1923 - val_accuracy: 0.9196
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2055 - accuracy: 0.9129 - val_loss: 0.1965 - val_accuracy: 0.9146
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2088 - accuracy: 0.9082 - val_loss: 0.1962 - val_accuracy: 0.9153
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2090 - accuracy: 0.9124 - val_loss: 0.1945 - val_accuracy: 0.9166
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2076 - accuracy: 0.9097 - val_loss: 0.1970 - val_accuracy: 0.9162
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2096 - accuracy: 0.9090 - val_loss: 0.2027 - val_accuracy: 0.9139
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2064 - accuracy: 0.9126 - val_loss: 0.1956 - val_accuracy: 0.9180
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.2063 - accuracy: 0.9128 - val_loss: 0.1947 - val_accuracy: 0.9180

In [47]:
model.save('model.h5')

c:\Users\Riyanshi Gupta\Classification_With_ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [54]:
%load_ext tensorboard
! pip install --upgrade setuptools

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
Requirement already satisfied: setuptools in .\venv\Lib\site-packages (82.0.1)
Collecting setuptools
  Downloading setuptools-83.0.0-py3-none-any.whl.metadata (6.6 kB)
Downloading setuptools-83.0.0-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/1.0 MB 12.0 MB/s  0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 82.0.1
    Uninstalling setuptools-82.0.1:
      Successfully uninstalled setuptools-82.0.1
Successfully installed setuptools-83.0.0

In [56]:
! pip install --upgrade tensorflow tensorboard
%reload_ext tensorboard
%tensorboard --logdir logs/fit

Requirement already satisfied: tensorflow in .\venv\Lib\site-packages (2.15.0)
Collecting tensorflow
  Downloading tensorflow-2.21.0-cp311-cp311-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.15.2)
Collecting tensorboard
  Using cached tensorboard-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=1.0.0 in .\venv\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in .\venv\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in .\venv\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in .\venv\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in .\venv\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in .\venv\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in .\venv\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorflow) (26.0)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in .\venv\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in .\venv\Lib\site-packages (from tensorflow) (83.0.0)
Requirement already satisfied: six>=1.12.0 in C:\Users\Riyanshi Gupta\AppData\Roaming\Python\Python311\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in .\venv\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in .\venv\Lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in .\venv\Lib\site-packages (from tensorflow) (1.14.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in .\venv\Lib\site-packages (from tensorflow) (1.82.1)
Collecting keras>=3.12.0 (from tensorflow)
  Using cached keras-3.15.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in .\venv\Lib\site-packages (from tensorflow) (1.26.4)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp311-cp311-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.10.2)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: wheel<1.0,>=0.23.0 in .\venv\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Collecting rich (from keras>=3.12.0->tensorflow)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.12.0->tensorflow)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.1-cp311-cp311-win_amd64.whl.metadata (32 kB)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.12.0->tensorflow)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Riyanshi Gupta\AppData\Roaming\Python\Python311\site-packages (from rich->keras>=3.12.0->tensorflow) (2.14.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.21.0-cp311-cp311-win_amd64.whl (350.8 MB)
   ---------------------------------------- 0.0/350.8 MB ? eta -:--:--
    --------------------------------------- 5.0/350.8 MB 25.2 MB/s eta 0:00:14
   - -------------------------------------- 11.8/350.8 MB 30.8 MB/s eta 0:00:12
   - -------------------------------------- 12.1/350.8 MB 26.0 MB/s eta 0:00:14
   - -------------------------------------- 12.6/350.8 MB 16.4 MB/s eta 0:00:21
   - -------------------------------------- 13.9/350.8 MB 13.9 MB/s eta 0:00:25
   - -------------------------------------- 15.5/350.8 MB 13.0 MB/s eta 0:00:26
   -- ------------------------------------- 17.8/350.8 MB 12.5 MB/s eta 0:00:27
   -- ------------------------------------- 20.2/350.8 MB 12.4 MB/s eta 0:00:27
   -- ------------------------------------- 22.8/350.8 MB 12.3 MB/s eta 0:00:27
   --- ------------------------------------ 26.5/350.8 MB 13.0 MB/s eta 0:00:25
   --- ------------------------------------ 29.9/350.8 MB 13.3 MB/s eta 0:00:25
   --- ------------------------------------ 33.8/350.8 MB 13.8 MB/s eta 0:00:24
   ---- ----------------------------------- 37.5/350.8 MB 14.0 MB/s eta 0:00:23
   ---- ----------------------------------- 39.6/350.8 MB 13.8 MB/s eta 0:00:23
   ---- ----------------------------------- 41.9/350.8 MB 13.5 MB/s eta 0:00:23
   ----- ---------------------------------- 44.6/350.8 MB 13.5 MB/s eta 0:00:23
   ----- ---------------------------------- 46.4/350.8 MB 13.2 MB/s eta 0:00:23
   ----- ---------------------------------- 48.5/350.8 MB 13.0 MB/s eta 0:00:24
   ----- ---------------------------------- 50.6/350.8 MB 12.9 MB/s eta 0:00:24
   ------ --------------------------------- 54.0/350.8 MB 13.1 MB/s eta 0:00:23
   ------ --------------------------------- 57.7/350.8 MB 13.3 MB/s eta 0:00:23
   ------ --------------------------------- 59.5/350.8 MB 13.1 MB/s eta 0:00:23
   ------- -------------------------------- 62.1/350.8 MB 13.1 MB/s eta 0:00:23
   ------- -------------------------------- 64.5/350.8 MB 13.0 MB/s eta 0:00:23
   ------- -------------------------------- 66.8/350.8 MB 13.0 MB/s eta 0:00:22
   ------- -------------------------------- 69.5/350.8 MB 13.0 MB/s eta 0:00:22
   -------- ------------------------------- 71.8/350.8 MB 12.9 MB/s eta 0:00:22
   -------- ------------------------------- 74.4/350.8 MB 12.9 MB/s eta 0:00:22
   -------- ------------------------------- 77.3/350.8 MB 12.9 MB/s eta 0:00:22
   --------- ------------------------------ 80.2/350.8 MB 13.0 MB/s eta 0:00:21
   --------- ------------------------------ 82.1/350.8 MB 12.8 MB/s eta 0:00:21
   --------- ------------------------------ 84.1/350.8 MB 12.8 MB/s eta 0:00:21
   --------- ------------------------------ 87.3/350.8 MB 12.8 MB/s eta 0:00:21
   ---------- ----------------------------- 89.7/350.8 MB 12.8 MB/s eta 0:00:21
   ---------- ----------------------------- 92.3/350.8 MB 12.7 MB/s eta 0:00:21
   ---------- ----------------------------- 94.6/350.8 MB 12.7 MB/s eta 0:00:21
   ----------- ---------------------------- 97.8/350.8 MB 12.8 MB/s eta 0:00:20
   ----------- --------------------------- 100.9/350.8 MB 12.9 MB/s eta 0:00:20
   ----------- --------------------------- 103.3/350.8 MB 12.8 MB/s eta 0:00:20
   ----------- --------------------------- 105.6/350.8 MB 12.8 MB/s eta 0:00:20
   ------------ -------------------------- 108.0/350.8 MB 12.7 MB/s eta 0:00:20
   ------------ -------------------------- 110.6/350.8 MB 12.7 MB/s eta 0:00:19
   ------------ -------------------------- 112.2/350.8 MB 12.6 MB/s eta 0:00:19
   ------------ -------------------------- 114.6/350.8 MB 12.6 MB/s eta 0:00:19
   ------------- ------------------------- 117.2/350.8 MB 12.6 MB/s eta 0:00:19
   ------------- ------------------------- 120.6/350.8 MB 12.7 MB/s eta 0:00:19
   ------------- ------------------------- 122.4/350.8 MB 12.6 MB/s eta 0:00:19
   ------------- ------------------------- 124.8/350.8 MB 12.6 MB/s eta 0:00:18
   -------------- ------------------------ 127.9/350.8 MB 12.6 MB/s eta 0:00:18
   -------------- ------------------------ 130.3/350.8 MB 12.6 MB/s eta 0:00:18
   -------------- ------------------------ 132.1/350.8 MB 12.5 MB/s eta 0:00:18
   -------------- ------------------------ 134.7/350.8 MB 12.5 MB/s eta 0:00:18
   --------------- ----------------------- 137.9/350.8 MB 12.6 MB/s eta 0:00:17
   --------------- ----------------------- 141.0/350.8 MB 12.7 MB/s eta 0:00:17
   --------------- ----------------------- 143.4/350.8 MB 12.6 MB/s eta 0:00:17
   ---------------- ---------------------- 145.2/350.8 MB 12.6 MB/s eta 0:00:17
   ---------------- ---------------------- 147.1/350.8 MB 12.5 MB/s eta 0:00:17
   ---------------- ---------------------- 149.7/350.8 MB 12.5 MB/s eta 0:00:17
   ---------------- ---------------------- 152.0/350.8 MB 12.5 MB/s eta 0:00:16
   ----------------- --------------------- 154.9/350.8 MB 12.5 MB/s eta 0:00:16
   ----------------- --------------------- 158.1/350.8 MB 12.6 MB/s eta 0:00:16
   ----------------- --------------------- 160.4/350.8 MB 12.5 MB/s eta 0:00:16
   ------------------ -------------------- 162.8/350.8 MB 12.5 MB/s eta 0:00:15
   ------------------ -------------------- 165.2/350.8 MB 12.5 MB/s eta 0:00:15
   ------------------ -------------------- 167.2/350.8 MB 12.5 MB/s eta 0:00:15
   ------------------ -------------------- 170.4/350.8 MB 12.5 MB/s eta 0:00:15
   ------------------- ------------------- 173.5/350.8 MB 12.6 MB/s eta 0:00:15
   ------------------- ------------------- 175.6/350.8 MB 12.5 MB/s eta 0:00:14
   ------------------- ------------------- 177.2/350.8 MB 12.5 MB/s eta 0:00:14
   ------------------- ------------------- 179.8/350.8 MB 12.5 MB/s eta 0:00:14
   -------------------- ------------------ 183.0/350.8 MB 12.5 MB/s eta 0:00:14
   -------------------- ------------------ 185.3/350.8 MB 12.5 MB/s eta 0:00:14
   -------------------- ------------------ 188.2/350.8 MB 12.5 MB/s eta 0:00:13
   --------------------- ----------------- 190.3/350.8 MB 12.5 MB/s eta 0:00:13
   --------------------- ----------------- 192.2/350.8 MB 12.5 MB/s eta 0:00:13
   --------------------- ----------------- 195.0/350.8 MB 12.5 MB/s eta 0:00:13
   ---------------------- ---------------- 198.2/350.8 MB 12.5 MB/s eta 0:00:13
   ---------------------- ---------------- 200.0/350.8 MB 12.5 MB/s eta 0:00:13
   ---------------------- ---------------- 202.4/350.8 MB 12.4 MB/s eta 0:00:12
   ---------------------- ---------------- 205.3/350.8 MB 12.5 MB/s eta 0:00:12
   ----------------------- --------------- 208.7/350.8 MB 12.5 MB/s eta 0:00:12
   ----------------------- --------------- 210.8/350.8 MB 12.5 MB/s eta 0:00:12
   ----------------------- --------------- 213.1/350.8 MB 12.5 MB/s eta 0:00:12
   ----------------------- --------------- 215.2/350.8 MB 12.5 MB/s eta 0:00:11
   ------------------------ -------------- 217.6/350.8 MB 12.4 MB/s eta 0:00:11
   ------------------------ -------------- 220.2/350.8 MB 12.4 MB/s eta 0:00:11
   ------------------------ -------------- 223.6/350.8 MB 12.5 MB/s eta 0:00:11
   ------------------------- ------------- 226.5/350.8 MB 12.5 MB/s eta 0:00:10
   ------------------------- ------------- 227.8/350.8 MB 12.4 MB/s eta 0:00:10
   ------------------------- ------------- 229.6/350.8 MB 12.4 MB/s eta 0:00:10
   ------------------------- ------------- 232.0/350.8 MB 12.4 MB/s eta 0:00:10
   -------------------------- ------------ 234.6/350.8 MB 12.4 MB/s eta 0:00:10
   -------------------------- ------------ 238.6/350.8 MB 12.5 MB/s eta 0:00:10
   -------------------------- ------------ 240.9/350.8 MB 12.5 MB/s eta 0:00:09
   -------------------------- ------------ 242.5/350.8 MB 12.4 MB/s eta 0:00:09
   --------------------------- ----------- 244.3/350.8 MB 12.4 MB/s eta 0:00:09
   --------------------------- ----------- 247.2/350.8 MB 12.4 MB/s eta 0:00:09
   --------------------------- ----------- 250.3/350.8 MB 12.4 MB/s eta 0:00:09
   ---------------------------- ---------- 253.2/350.8 MB 12.4 MB/s eta 0:00:08
   ---------------------------- ---------- 255.1/350.8 MB 12.4 MB/s eta 0:00:08
   ---------------------------- ---------- 257.7/350.8 MB 12.4 MB/s eta 0:00:08
   ---------------------------- ---------- 260.3/350.8 MB 12.4 MB/s eta 0:00:08
   ----------------------------- --------- 262.4/350.8 MB 12.4 MB/s eta 0:00:08
   ----------------------------- --------- 265.6/350.8 MB 12.3 MB/s eta 0:00:07
   ----------------------------- --------- 267.6/350.8 MB 12.3 MB/s eta 0:00:07
   ------------------------------ -------- 270.8/350.8 MB 12.2 MB/s eta 0:00:07
   ------------------------------ -------- 273.2/350.8 MB 12.1 MB/s eta 0:00:07
   ------------------------------ -------- 275.0/350.8 MB 12.3 MB/s eta 0:00:07
   ------------------------------ -------- 277.9/350.8 MB 12.4 MB/s eta 0:00:06
   ------------------------------- ------- 280.5/350.8 MB 12.4 MB/s eta 0:00:06
   ------------------------------- ------- 282.9/350.8 MB 12.4 MB/s eta 0:00:06
   ------------------------------- ------- 285.5/350.8 MB 12.4 MB/s eta 0:00:06
   -------------------------------- ------ 288.9/350.8 MB 12.4 MB/s eta 0:00:06
   -------------------------------- ------ 291.2/350.8 MB 12.4 MB/s eta 0:00:05
   -------------------------------- ------ 293.3/350.8 MB 12.3 MB/s eta 0:00:05
   -------------------------------- ------ 295.2/350.8 MB 12.2 MB/s eta 0:00:05
   --------------------------------- ----- 298.1/350.8 MB 12.2 MB/s eta 0:00:05
   --------------------------------- ----- 300.7/350.8 MB 12.2 MB/s eta 0:00:05
   --------------------------------- ----- 303.0/350.8 MB 12.2 MB/s eta 0:00:04
   --------------------------------- ----- 305.1/350.8 MB 12.2 MB/s eta 0:00:04
   ---------------------------------- ---- 307.5/350.8 MB 12.2 MB/s eta 0:00:04
   ---------------------------------- ---- 310.6/350.8 MB 12.3 MB/s eta 0:00:04
   ---------------------------------- ---- 312.7/350.8 MB 12.3 MB/s eta 0:00:04
   ----------------------------------- --- 315.4/350.8 MB 12.3 MB/s eta 0:00:03
   ----------------------------------- --- 318.5/350.8 MB 12.2 MB/s eta 0:00:03
   ----------------------------------- --- 319.8/350.8 MB 12.2 MB/s eta 0:00:03
   ----------------------------------- --- 321.4/350.8 MB 12.2 MB/s eta 0:00:03
   ----------------------------------- --- 323.2/350.8 MB 12.1 MB/s eta 0:00:03
   ------------------------------------ -- 325.1/350.8 MB 12.1 MB/s eta 0:00:03
   ------------------------------------ -- 327.7/350.8 MB 12.1 MB/s eta 0:00:02
   ------------------------------------ -- 331.1/350.8 MB 12.1 MB/s eta 0:00:02
   ------------------------------------- - 333.4/350.8 MB 12.1 MB/s eta 0:00:02
   ------------------------------------- - 336.6/350.8 MB 12.2 MB/s eta 0:00:02
   ------------------------------------- - 338.4/350.8 MB 12.1 MB/s eta 0:00:02
   ------------------------------------- - 340.8/350.8 MB 12.1 MB/s eta 0:00:01
   --------------------------------------  343.9/350.8 MB 12.2 MB/s eta 0:00:01
   --------------------------------------  347.1/350.8 MB 12.2 MB/s eta 0:00:01
   --------------------------------------  349.4/350.8 MB 12.2 MB/s eta 0:00:01
   --------------------------------------  350.7/350.8 MB 12.1 MB/s eta 0:00:01
   --------------------------------------  350.7/350.8 MB 12.1 MB/s eta 0:00:01
   --------------------------------------  350.7/350.8 MB 12.1 MB/s eta 0:00:01
   ---------------------------------------- 350.8/350.8 MB 11.8 MB/s  0:00:29
Downloading h5py-3.14.0-cp311-cp311-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   -------------- ------------------------- 1.0/2.9 MB 5.6 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 6.7 MB/s  0:00:00
Downloading ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl (210 kB)
Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Downloading tensorboard-2.21.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ------------------- -------------------- 2.6/5.5 MB 12.5 MB/s eta 0:00:01
   -------------------------------------- - 5.2/5.5 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 12.5 MB/s  0:00:00
Using cached keras-3.15.0-py3-none-any.whl (1.7 MB)
Using cached namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.1-cp311-cp311-win_amd64.whl (337 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, protobuf, optree, ml_dtypes, mdurl, h5py, tensorboard, markdown-it-py, rich, keras, tensorflow

  Attempting uninstall: protobuf

    Found existing installation: protobuf 4.25.9

    Uninstalling protobuf-4.25.9:

      Successfully uninstalled protobuf-4.25.9

   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   --- ------------------------------------  1/11 [protobuf]
   ------- --------------------------------  2/11 [optree]
  Attempting uninstall: ml_dtypes
   ------- --------------------------------  2/11 [optree]
    Found existing installation: ml-dtypes 0.2.0
   ------- --------------------------------  2/11 [optree]
   ---------- -----------------------------  3/11 [ml_dtypes]
    Uninstalling ml-dtypes-0.2.0:
   ---------- -----------------------------  3/11 [ml_dtypes]
      Successfully uninstalled ml-dtypes-0.2.0
   ---------- -----------------------------  3/11 [ml_dtypes]
   ---------- -----------------------------  3/11 [ml_dtypes]
   ---------- -----------------------------  3/11 [ml_dtypes]
   ---------- -----------------------------  3/11 [ml_dtypes]
   ---------- -----------------------------  3/11 [ml_dtypes]
   ---------- -----------------------------  3/11 [ml_dtypes]
   ---------- -----------------------------  3/11 [ml_dtypes]
   ---------- -----------------------------  3/11 [ml_dtypes]
   ---------- -----------------------------  3/11 [ml_dtypes]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Riyanshi Gupta\Classification_With_ANN\venv\Lib\site-packages\google\~upb'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Riyanshi Gupta\Classification_With_ANN\venv\Lib\site-packages\~l_dtypes'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Riyanshi Gupta\Classification_With_ANN\venv\Lib\site-packages\~5py'.
  You can safely remove it manually.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Riyanshi Gupta\\Classification_With_ANN\\venv\\Lib\\site-packages\\tensorflow\\compiler\\mlir\\quantization\\tensorflow\\python\\pywrap_quantize_model.pyd'
Consider using the `--user` option or check the permissions.

In [60]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 2040), started 0:04:46 ago. (Use '!kill 2040' to kill it.)