In [11]:
import sys
print(sys.executable)

c:\Users\Riyanshi Gupta\Classification_With_ANN\venv\python.exe

In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd
import pickle

In [8]:
#load the model, scaler and label encoder
model = load_model('model.h5')
with open('labelencoder_gender.pkl', 'rb') as f:
    label_encoder = pickle.load(f)
      
with open('onehotencoder.pkl', 'rb') as f:
    label_encoder_geo = pickle.load(f)

with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

c:\Users\Riyanshi Gupta\Classification_With_ANN\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.

In [9]:
input_data ={
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Female', 
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000, 
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [12]:
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_df

c:\Users\Riyanshi Gupta\Classification_With_ANN\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [17]:
input_df=pd.DataFrame([input_data])
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France  Female  ...          1               1            50000

[1 rows x 10 columns]

In [18]:
#encode categorical variables
input_df['Gender'] = label_encoder.transform(input_df['Gender'])
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       0  ...          1               1            50000

[1 rows x 10 columns]

In [20]:
#concatenate thhe one hot encoded columns with the input dataframe
input_df = pd.concat([input_df.drop('Geography', axis=1), geo_df], axis=1)

In [21]:
#scaling the inpput data
scaled_input = scaler.transform(input_df)

In [22]:
scaled_input

array([[-0.52111599, -1.09168714,  0.10961719, -0.68538967, -0.2569057 ,
         0.8095029 ,  0.64259497,  0.9687384 , -0.87203322,  0.98560362,
        -0.5698444 , -0.57369368]])

In [23]:
#predict churn
prediction = model.predict(scaled_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step

In [25]:
prediction

array([[0.05060008]], dtype=float32)

In [28]:
prediction_proba = prediction[0][0]
prediction_proba

0.050600078

In [31]:
if prediction_proba > 0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is unlikely to churn.")

The customer is unlikely to churn.